[package]
name = "warsim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kdam = "0.5.0"
rand = "0.8.5"
